server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/book-catalog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
